# Initializes the sqlserver container with a user for the API tests.
#
# This is separated out because not all test cases need it.

# If you are using this, it's recommended that you add this block to your sqlserver container definition:
#
#     depends_on:
#       sqlserver:
#         condition: service_started

version: "3.6"

services:
  sqlserver-init:
    image: mcr.microsoft.com/mssql-tools
    command:
      - /init.sh
    environment:
      SERVER_HOST: sqlserver
      SA_PASSWORD: "Password!"
    volumes:
      - ./init.sh:/init.sh
      - ./init.sql:/init.sql
